skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
prediction_market = "D3R2C6F5eX9gV4iA3w7K81L6m2N5p9x8y7z4w6v1u2i"

[programs.devnet]
prediction_market = "D3R2C6F5eX9gV4iA3w7K81L6m2N5p9x8y7z4w6v1u2i"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
